version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: DB
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  db_migrations:
    build: db_migrations
    depends_on:
      - db
    env_file:
      - .env
  auth:
    develop:
      watch:
        - action: sync+restart
          path: ./auth
          target: /app
          ignore:
            - coverage/
            - node_modules/
            - dist/
    build: auth
    depends_on:
      - db
      - db_migrations
    ports:
      - '8000:8000'
    env_file:
      - .env
  server:
    develop:
      watch:
        - action: sync+restart
          path: ./server
          target: /app
          ignore:
            - coverage/
            - node_modules/
            - dist/
    build: server
    depends_on:
      - db
      - db_migrations
    ports:
      - '8080:8080'
    env_file:
      - .env
  client:
    develop:
      watch:
        - action: sync+restart
          path: ./client
          target: /app
          ignore:
            - coverage/
            - node_modules/
            - dist/
    build: client
    depends_on:
      - auth
      - server
    ports:
      - '3000:3000'
    env_file:
      - .env
volumes:
  db_data:
